name = "samrituddam"
main = "./.output/server/index.mjs"
compatibility_date = "2025-03-15"

[build]
command = "npm install && npm run build"

[site]
bucket = "./.output/public"
exclude = []

[env.production]
workers_dev = false
route = "https://samrituddam.com/*"
main = ".output/server/index.mjs" 

[[rules]]
type = "Data"
globs = ["**/*.{json,png,jpg,jpeg,gif,svg}"]
fallthrough = true