name = "samrituddam"
main = "./.output/server/index.mjs"
compatibility_date = "2025-03-15"

[build]
command = "npm run build"

[site]
bucket = "./.output/public" 

[env.production]
workers_dev = false
route = "https://samrituddam.samrituddam20.workers.dev/*"
main = "./.output/server/index.mjs"